### ISSUE TITLE
How to consume an authenticated WebSocket using a JS client?

### ISSUE THREAD

**Issue by lamba92** [ktorio/ktor#1016]
I need to send the log of the server through a WebSocket and it works just fine. Now I want use an authenticated route but I cannot find a client that has Auth built in.

If I am not mistaken the Ktor JS client does not allow WebSockets. 
Is the CIO engine available for JS? If so we're I could find some documentation oh how to use it?
Of course would need to add it to my project, which happens to be an Angular7 SPA. How do I output all the stuff including the Kotlin stdlib-js?

**Comment by e5l** [comment]
Hi @lamba92, `ktor-client-js` implements websockets in `1.2.0-alpha-1`

**Comment by lamba92** [comment]
Wold it be possible to use it directly into TypeScript? If not, can you provide some advice on how to create a Gradle project with all the necessary dependencies and how to output something usable inside an Angular project? I have very little experience with JS in general and Kotlin/JS as well.

**Comment by lamba92** [comment]
Well I think I [managed to wrap](https://github.com/lamba92/easy-ws/blob/master/src/main/kotlin/it.lamba/Main.kt) (in)decently the Ktor client so that it's almost transparently usable from JS. Now how do correctly import what is outputted from this build into any JS project?

**Comment by anton-bannykh** [comment]
@lamba92 Kotlin/JS exports every public declaration as `your.package.name.Declaration`. That means that from a javascript project you should be able consume the resulting `<your-module-name>.js`  file regularly (e.g. `var foo = require('some/path/<your-module-name>.js'`) and then use it like so: `new foo.your.package.name.Declaration("Hi1")`

Keep in mind that you need to choose the correct module kind when compiling your module to JS, otherwise your environment won't be able to load it: https://kotlinlang.org/docs/tutorials/javascript/working-with-modules/working-with-modules.html

When in doubt I suggest `umd`, as it covers most use-cases.

**Comment by e5l** [comment]
Hi @lamba92, do you have any questions remaining?

**Comment by e5l** [comment]
Closed. Feel free to reopen if the issue is active.

**Comment by lamba92** [comment]
Turns out the plain JS `WebSocket` class can handle it very well. Thanks to [this](https://stackoverflow.com/a/41521871/2331319) answer on StackOverflow I was able to set the header without any external library. Still lame the fact that Angular HttpClient does not support websockets out of the box.
