### ISSUE TITLE
Memory leak in most simple example in 1.1.3

### ISSUE THREAD

**Issue by lukas1** [ktorio/ktor#1059]
### Ktor Version
`1.1.3`

### Ktor Engine Used(client or server and name)
server `Netty`

### JVM Version, Operating System and Relevant Context
OSX `java version "10.0.1" 2018-04-17`

### Feedback
I've created a very minimalistic example of a `ktor` application that just responds to `/` with HTTP Code `200` and nothing more. In this example, I am observing increased memory usage of the process, but this allocated memory doesn't seem to deallocate ever.

I'm attaching example project to download and example code too.

### Steps used to reproduce
1. Start the application
2. Find its PID via `jps` command, the one that's called `EngineMain`
3. Observe memory usage of this process by `top -pid PID_OF_THE_KTOR_APP`, in the column `MEM`
4. Launch hundreds of requests: `for i in `seq 10000`; do curl -i http://0.0.0.0:8080/; done`
5. Observe `MEM` in the running `top` tool.

### Expected behavior
Memory usage should not increase drastically and after the command is finished and all requests are finished, memory usage should decrease, return to its starting value

### Actual behavior
Memory usage is increased visibly and never decreased. Memory usage keeps rising and rising, never to be deallocated.

Am I just doing something wrong?

### Example

Example code:
```
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
fun Application.module() {
    routing {
        get("/") {
            call.respond(HttpStatusCode.OK)
        }
    }
}
```

Example project to download:
[ktor-example.zip](https://github.com/ktorio/ktor/files/3046616/ktor-example.zip)

**Comment by cy6erGn0m** [comment]
Just have completed your steps and don't see any noticeable memory usage growth: the application didn't even take 24mb heap. 

![Screenshot_20190408_194029](https://user-images.githubusercontent.com/762598/55741539-2e1e9200-5a36-11e9-853a-233e522c2b8a.png)

![Screenshot_20190408_194337](https://user-images.githubusercontent.com/762598/55741719-9a999100-5a36-11e9-84ef-c4b0ee1e4834.png)

Are you sure you don't have any tool/profiler that could connect to a running instance that may cause leak?

**Comment by cy6erGn0m** [comment]
Same on macos X:

<img width="873" alt="Screenshot 2019-04-08 at 20 02 40" src="https://user-images.githubusercontent.com/762598/55742821-578ced00-5a39-11e9-9572-225f1b0f3bf0.png">

The maximum memory size I did observe is 128M

**Comment by lukas1** [comment]
Out of curiosity, did you use my `.zip`, or did you create the project from scratch, using source code in the comment?

Previously, I've been running the app from IntelliJ. Just to rule out influence of Intellij on the measurement, I've modified `build.gradle` file of the example, to add a new gradle task, to export the project into a 'fat' jar:

```
task fatJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'title',
                'Implementation-Version': version,
                'Main-Class': 'io.ktor.server.netty.EngineMain'
    }
    baseName = project.name
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
```

Using this task, I've exported the application into a jar and then I've runned this jar using:
```
java -jar example-0.0.1.jar
```

Again, I've found PID of the running application and using `top -pid PID_OF_THE_KTOR_APP` I'm observing memory usage of the app.

Running again:
```
for i in `seq 10000`; do curl -i http://0.0.0.0:8080/; done
```

I've kept observing memory increases:
<img width="582" alt="Screenshot 2019-04-09 at 13 26 30" src="https://user-images.githubusercontent.com/370592/55796823-28bf5700-5acb-11e9-86c2-5205ae0b87f0.png">

And later:
<img width="577" alt="Screenshot 2019-04-09 at 13 28 59" src="https://user-images.githubusercontent.com/370592/55796949-7b007800-5acb-11e9-96aa-9fc34a01828c.png">

Memory doesn't seem to be released even after minutes of running the service idle, without making any requests to it.

I'm observing similar behavior when running the app bundled into a Docker Image on AWS Fargate. 

I'm attaching the jar in question:

[example-0.0.1.jar.zip](https://github.com/ktorio/ktor/files/3058705/example-0.0.1.jar.zip)

I have reproduced the same problem with this jar on other OSX machine and therefore I believe there really is a problem with this specific jar.

I wonder what's the difference between our testing steps. Perhaps we've compiled the app using different version of Kotlin, or something like that?

**Comment by cy6erGn0m** [comment]
Yes, I tried your zip.
Most likely it is just what hotspot consume (such as JIT code cache), nothing ktor specific.

**Comment by lukas1** [comment]
But wouldn't you expect the memory usage to decrease over time? The app only ever increases its memory usage and it leads to Out Of Memory errors eventually. It's not usable for production environment like this. Do you have any suggestions as to what could I try to get the memory released?

Also, as I've mentioned, I reproduced the issue on at least two machines and on AWS Fargate as well. I do feel like it must be something Ktor specific. I've only noticed this behavior on Ktor apps. I don't believe it is just something specific to my environment.

**Comment by fgutmann** [comment]
My testing also shows no signs of problems. Even with 16 mb of heap everything runs smoothly after more than 60 million requests.

`java -Xms16M -Xmx16M -jar example-0.0.1.jar`

```
> $ wrk -c 50 -t 50 -d 10m http://localhost:8080
Running 10m test @ http://localhost:8080
  50 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.32ms  767.00us  69.07ms   93.99%
    Req/Sec   781.35     64.03     1.62k    84.06%
  23332766 requests in 10.00m, 845.57MB read
Requests/sec:  38881.16
Transfer/sec:      1.41MB
```

Memory usage of the process grew slightly in the first 10 minutes, topping out at 115 MB. Even after 2 more runs of the above `wrk` command it stayed constant.

Also no signs of memory leaks observed in visualvm. Class count stayed pretty stable at around 1470 and heap never became an issue. It always fit nicely within the 16 MB.

<img width="957" alt="Screenshot 2019-04-11 at 17 24 33" src="https://user-images.githubusercontent.com/236795/55974107-dc1c7d00-5c7e-11e9-865c-0411d5b1a321.png">

> But wouldn't you expect the memory usage to decrease over time? 

No, the jvm by default doesn't give away heap memory after it once allocated it. It will take up to to the specified maximum (Xmx) happily and keep it. Since you didn't specify a maximum heap size in your runs, it could have been very high.

> The app only ever increases its memory usage and it leads to Out Of Memory errors eventually. It's not usable for production environment like this. Do you have any suggestions as to what could I try to get the memory released?

It should not be necessary to relase unused heap. Just specify the maximum amount you have available, taking into account other non-heap memory needed by the jvm.

If you re-run your test with a fixed `Xmx` and `Xms` value, you probably will observe more stable memory behaviour.

**Comment by fgutmann** [comment]
My testing also shows no signs of problems. Even with 16 mb of heap everything runs smoothly after more than 60 million requests.

`java -Xms16M -Xmx16M -jar example-0.0.1.jar`

```
> $ wrk -c 50 -t 50 -d 10m http://localhost:8080
Running 10m test @ http://localhost:8080
  50 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.32ms  767.00us  69.07ms   93.99%
    Req/Sec   781.35     64.03     1.62k    84.06%
  23332766 requests in 10.00m, 845.57MB read
Requests/sec:  38881.16
Transfer/sec:      1.41MB
```

Memory usage of the process grew slightly in the first 10 minutes, topping out at 115 MB. Even after 2 more runs of the above `wrk` command it stayed constant.

Also no signs of memory leaks observed in visualvm. Class count stayed pretty stable at around 1470 and heap never became an issue. It always fit nicely within the 16 MB.

<img width="957" alt="Screenshot 2019-04-11 at 17 24 33" src="https://user-images.githubusercontent.com/236795/55974107-dc1c7d00-5c7e-11e9-865c-0411d5b1a321.png">

> But wouldn't you expect the memory usage to decrease over time? 

No, the jvm by default doesn't give away heap memory after it once allocated it. It will take up to to the specified maximum (Xmx) happily and keep it. Since you didn't specify a maximum heap size in your runs, it could have been very high.

> The app only ever increases its memory usage and it leads to Out Of Memory errors eventually. It's not usable for production environment like this. Do you have any suggestions as to what could I try to get the memory released?

It should not be necessary to relase unused heap. Just specify the maximum amount you have available, taking into account other non-heap memory needed by the jvm.

If you re-run your test with a fixed `Xmx` and `Xms` value, you probably will observe more stable memory behaviour.

**Comment by cy6erGn0m** [comment]
> The app only ever increases its memory usage and it leads to Out Of Memory errors eventually.

Do you actually have OOM? How long run did you try?

**Comment by cy6erGn0m** [comment]
@fgutmann  btw, G1 may release heap memory. However since direct byte buffer are allocated off-heap and they are pooled this is why it could lead to non-releasable memory consumption but it is not growing constantly and the growth should stop once the pool size limit is reached

**Comment by lukas1** [comment]
> Do you actually have OOM? How long run did you try?

Actually looks like I don't get OOM. I'll play with setting up some limits for the heap. Thanks for suggestions.

**Comment by fgutmann** [comment]
>  btw, G1 may release heap memory.
Thanks for the info. I thought this wouldn't be active by default.

**Comment by lukas1** [comment]
I have some new information regarding this issue. It really looks like the memory usage on my Mac plateaus at some arbitrary value and then doesn't increase after that. In my original tests I didn't perform the test long enough to see that effect happening.

What started me looking into this was, that I observed on a different Ktor app running in a docker image on AWS Fargate that it kept being restarted after few hours of running, due to memory usage. 

After the discussion in this issue, I've looked through logs and I've never gotten any OOM exception, so I've looked at the issue from a different perspective.

With some bit of a research and testing, I've found that the likely culprit for what happened is, that I've been running my app in an docker image based on `openjdk:8-jre-alpine` image. 

While, I did use `-XX:+UseCGroupMemoryLimitForHeap` and all the other related flags, this did not help it seems, and the JVM happily continued allocating new memory ignoring the CGroup memory limit of the running image.

Switching to `openjdk:10` has helped and the memory usage of the app is now stable. Thank you for your suggestions, they pushed me in the right direction when investigating the issue. I hope this comment can help somebody else in the future.

With that, I'm closing this issue as resolved!
