### ISSUE TITLE
Raw sockets problem

### ISSUE THREAD

**Issue by indrih17** [ktorio/ktor#1273]
**Ktor Version and Engine Used (client or server and name)**
Ktor raw sockets version 1.2.3
java version jdk 12
Linux ubuntu version 19.04

**Describe the bug**
I copied the code from here to myself https://ktor.io/servers/raw-sockets.html.
The documentation is out of date: the `writeBytes` method no longer exists. 
I took the `write` method instead, but when I get a server response, the client crashes with an error.

**Screenshots**
![Screenshot of error stacktrace](https://user-images.githubusercontent.com/20010903/62704240-8faa3980-b9f3-11e9-9a96-f9a99c8453e9.png)

**Comment by dmitrievanthony** [comment]
Hi @indrih17, thanks for reporting.

Well, I spent some time trying to reproduce the issue. However, in my examples, everything works fine (we need to use `write` instead of `writeBytes` for sure). I prepared [this project ](https://github.com/dmitrievanthony/KPlayground/blob/%231273/src/main/kotlin/server.kt) that should reproduce the problem. Could you check if it fails in your environment? If it works fine, could you also provide some other example?

**Comment by dmitrievanthony** [comment]
I also prepared https://github.com/ktorio/ktorio.github.io/pull/252 to fix documentation.

**Comment by dmitrievanthony** [comment]
Well, I see the corresponding PR merged so I'm closing the issue. Feel free to reopen it in case of any questions.
