### ISSUE TITLE
Support Sealed Classes inside Session-Objects

### ISSUE THREAD

**Issue by d3xter** [ktorio/ktor#129]

**Comment by cy6erGn0m** [comment]
Currently the default serializer doesn't provide ability to serialize/deserialize nested objects, only primitive types, collections (lists, sets and maps) and enums (will be available since 0.3.3). Object graphs are not yet supported and it is still open question if we should provide this functionality.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-826">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
