### ISSUE TITLE
handle in Route not executing lambda

### ISSUE THREAD

**Issue by lamba92** [ktorio/ktor#1303]
**Ktor Version and Engine Used (client or server and name)**
Ktor v1.2.3, TestApplicationEngine

**Describe the bug**
I am building a Feature for rest repositories, when registering the routes for a specified `HttpMethod`, the lambda passed to the `handle` method is never executed. Here my repo's [issue](https://github.com/lamba92/ktor-rest-repositories/issues/2)

**To Reproduce**
[Here](https://github.com/lamba92/ktor-rest-repositories/blob/master/src/test/kotlin/com/github/lamba92/ktor/features/test/Test.kt)'s the code to reproduce it. Strangely the response is `null`, check out the test results on TravisCI [here](https://travis-ci.org/lamba92/ktor-rest-repositories/jobs/577534481#L335) .

**Comment by lamba92** [comment]
May be related to [this](https://github.com/lamba92/ktor-rest-repositories/issues/1).

**Comment by cy6erGn0m** [comment]
The first bug I've noticed is in Utils.kt lines 49 and 61: entityIdTag should be placed inside of `{}`, otherwise it leads to a constant path requirement, for example `repositories/intidentities/entityIdTag` that is never requested, should be 
`repositories/intidentities/{entityIdTag}`.

After fixing this, `integer entities test` still still no luck: the second request is PUT but your repository is creating Post routes instead.

Also, when sending a request body, one should also provide `Content-Type` request header, otherwise a server may respond with 415 Unsupported Media Type.

**Comment by cy6erGn0m** [comment]
Also, you can use routing resolution trace for debugging complex routing trees:

```kotlin
    routing {
        trace { trace ->
            println(trace.buildText())
        }
    }
```

See https://ktor.io/servers/features/routing.html#tracing

**Comment by lamba92** [comment]
Thank you very much! Using the trace function (which I was not aware at all) I discovered that the problems were indeed the Content-Type for multiple items and the forgotten parenthesis for both single and multiple items!
