### ISSUE TITLE
Add support for tvOS and watchOS-based targets

### ISSUE THREAD

**Issue by sbogolepov** [ktorio/ktor#1378]
**Subsystem**
Client.

**Describe the solution you'd like**
Kotlin/Native 1.3.60 will add support for tvOS and watchOS-based targets.
Since these targets are similar to iOS-based targets, adding them to the appropriate `build.gradle` should be sufficient. 
Targets:
* watchos_x86
* watchos_arm32
* watchos_arm64
* tvos_x64
* tvos_arm64

**Comment by cy6erGn0m** [comment]
Do we think that ktor client may fit into a watch device?

**Comment by gabrielittner** [comment]
From what I can see tvos and watchos have been added here https://github.com/ktorio/ktor/blob/master/gradle/posix.gradle so that there are artifacts of `ktor-client-core` and others for tvos and watchos.

What is still missing is a specific client implementation for both platforms. From a test adding the new targets to https://github.com/ktorio/ktor/blob/master/gradle/posix.gradle produces a version of `ktor-client-ios` that works on tvOS. Despite it's name the artifact is already used for mac os as well. Is there anything that speaks against adding the targets there?

**Comment by e5l** [comment]
Hi @gabrielittner, the `ktor-client-ios` implementation should work fine for all new platforms.

Closed

**Comment by gabrielittner** [comment]
@e5l Thanks for the reply. My second link was supposed to go to https://github.com/ktorio/ktor/blob/master/gradle/darwin.gradle where the new platforms were not added. Because of that `ktor-client-ios` isn't usable on tvOS/watchOS yet in the recent 1.3.0-beta-2.

**Comment by cy6erGn0m** [comment]
It looks like all watchos targets should be disabled in 1.3.0 due to `CFNetwork` module that is missing on watchos. I know that it is listed in the docs as present but it is actually missing.

**Comment by dmitrish** [comment]
So what's the current state for ktor client for watchOS? Tried using ktor-client-ios but it wouldn't compile for watchOS target

**Comment by dmitrish** [comment]
<img width="383" alt="Screen Shot 2019-12-15 at 12 52 03 PM" src="https://user-images.githubusercontent.com/38740872/70866599-b516f900-1f39-11ea-809b-a409b8ae5211.png">

unable to resolve for watchOS targets
