### ISSUE TITLE
iOS Memory Leak when KTOR Get Request is Made

### ISSUE THREAD

**Issue by Tony-T-R-A-N** [ktorio/ktor#1420]
Hello, I am having an issue with iOS memory leaks when I make a ktor get request.
The dispatcher is being built on the iosX64/iosArm32/iosArm32 side through an class implementing CoroutineDispatcher() with the override fun dispatch doing
```
dispatch_async(dispatch_get_main_queue()) {
    block.run()
}
```
```
class DummyClass() : CoroutineScope {
​
	override val coroutineContext: CoroutineContext
        get() = dispatcher
	
	fun execute(suspendFunc: suspend () -> Unit) {
		launch { suspendFunc() }
	}    
​
	fun request(
		parameter: String,
		callback: (MyResponse?, Throwable?) -> Unit
	) {
		execute {
			try {
				val result = httpClient.get<MyResponse> {
					url("PUT A URL HERE")
				}
​
				callback(result, null)
			} catch (e: Throwable) {
				callback(null, e)
			} finally {
				executor.cancel()
			}
		}
	}
	
}
```

**Comment by bherbst** [comment]
I spent some time over the last few days digging into this issue, and believe I have found the issue (and solved it).

### Background
We made a sample app that simply makes 300 API calls in quick succession in order to (roughly) test Ktor's performance and memory profile. 

As it stands today (with Ktor 1.3.0-beta-2), the memory profile looks something like this, with the peak of the graph being roughly 122MB:

![ktor_leak_graph](https://user-images.githubusercontent.com/3267925/70550277-21a98680-1b3b-11ea-9d30-cd83eb077df2.png)

Looking at what is leaking, it appears as though the biggest source is a large number of 96KB mallocs in `SSLBuffer`, which are tracked on the green graph above. Here's a breakdown of some of those allocations and a stack trace:

![ktor_leaked_objects](https://user-images.githubusercontent.com/3267925/70550379-44d43600-1b3b-11ea-8f7b-45b288093524.png)

![ktor_leak_trace](https://user-images.githubusercontent.com/3267925/70550432-5a496000-1b3b-11ea-8c97-caf4f9ba7777.png)

After looking through the call traces for these allocations, it appears as though the entire coroutine used for making the request was leaked, and these objects just happened to be the biggest single object connected to that leak.

### The fix
Ktor's iOS client engine currently opens an `NSUrlSession` using [`sessionWithConfiguration()`](https://developer.apple.com/documentation/foundation/nsurlsession/1411597-sessionwithconfiguration?language=objc), which carries this warning for the `delegate` parameter:

> **Important**
> 
> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session by calling the `invalidateAndCancel` or `finishTasksAndInvalidate` method, your app leaks memory until it exits.

After forking `IosClientEngine` and adding a call to `finishTasksAndInvalidate()` at the end, the leak appears to be fixed and the memory consumption graph looks like this (again, the 96KB `SSLBuffer` allocations are shown in the green graph):

![ktor_ios_leak_fixed](https://user-images.githubusercontent.com/3267925/70550642-ac8a8100-1b3b-11ea-946e-c0bc122f2568.png)

These allocations appear to be properly collected now, and no longer leak.

**Comment by e5l** [comment]
Fixed in `master`
