### ISSUE TITLE
Very long startup time

### ISSUE THREAD

**Issue by rekire** [ktorio/ktor#1474]
**Ktor Version and Engine Used (client or server and name)**
ktor client 1.2.6

**Describe the bug**
I have no idea why, but the creation of the http client takes almost 2,000ms. I was able to speedup my code by lazyloading the client.

**To Reproduce**
Write a class with a httpClient property like here:

    private val httpClient =
        HttpClient(OkHttp) {
            install(JsonFeature) {
                serializer = GsonSerializer()
                acceptContentTypes += ContentType("application", "json+hal")
            }
        }

When the property is not lazy loaded it takes 2s longer.

**Expected behavior**
A creation of the http client should not take seconds it should take ms.

**Comment by e5l** [comment]
Hi @rekire, thanks for the report. 
Could you manage this for the `Android` engine? Just curiosity :)

**Comment by rekire** [comment]
I'll check it, however I'm using it in a CLI tool. Can you give me the required dependency?

**Comment by e5l** [comment]
Sure: "io.ktor:ktor-client-android:$ktor_version"

**Comment by rekire** [comment]
That engine takes just 100-200ms.

**Comment by dmitrievanthony** [comment]
Hi @rekire ,

I prepared a [simple benchmark](https://github.com/dmitrievanthony/KPlayground/tree/%231474/src/main/kotlin) to test the behavior of the `OkHttp` client. The results are the following on my machine:

__Ktor with `OkHttp` as an engine and `Gson` (see the [code](https://github.com/dmitrievanthony/KPlayground/blob/%231474/src/main/kotlin/app.kt)):__
```
HttpClient: Single shot time: 286.304052 ms/op
HttpClient: Average time: 0.18461444 ms/op
```

__Pure `OkHttpClient` instantiation (see the [code](https://github.com/dmitrievanthony/KPlayground/blob/%231474/src/main/kotlin/app-pure-okhttp.kt)):__
```
OkHttp: Single shot time: 217.042959 ms/op
OkHttp: Average time: 0.13395459199999998 ms/op
```

__Pure `Gson` instantiation (see the [code](https://github.com/dmitrievanthony/KPlayground/blob/%231474/src/main/kotlin/app-pure-gson.kt)):__
```
Gson: Single shot time: 46.729684 ms/op
Gson: Average time: 0.006612668 ms/op
```

It seems like Ktor doesn't introduce any additional latency, the time is spent on [OkHttpClient](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/) instantiation and [Gson](https://www.javadoc.io/doc/com.google.code.gson/gson/2.6/index.html) instantiation. So that Ktor can't improve this behavior in any way.

Meanwhile, during my investigation, I found out that approximately 30% of `OkHttpClient` instantiation time spent on `java.security.*` initialization. If you don't use SSL for some reason you can turn it off and so that get a speedup.
