### ISSUE TITLE
Wrong Redirection

### ISSUE THREAD

**Issue by nectar1** [ktorio/ktor#1623]
**Ktor Version and Engine Used (client or server and name)**
1.3.0, client

**Describe the bug**
If response contains "Location" and status 302
So according to https://en.wikipedia.org/wiki/HTTP_302 
the request type of the new request change to GET

But in the current version the method of a new request is still the same as an original request

**Comment by nectar1** [comment]
Also I see more serious problem with cookies of 302 Response, them are not applied on a new request

**Comment by cy6erGn0m** [comment]
https://ktor.io/clients/http-client/features/http-cookies.html

**Comment by dmitrievanthony** [comment]
Hi @nectar1,

Taking into account [RFC1945](https://tools.ietf.org/html/rfc1945) (HTTP 1.0) the behavior you described is incorrect because the RFC states that:

> Note: When automatically redirecting a POST request after
       receiving a 302 status code, some existing user agents will
       **erroneously** change it into a GET request.

At the same time, [RFC7231](https://tools.ietf.org/html/rfc7231) (HTTP 1.1) states that:

> Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.

But it's still an optional behavior (I guess it was introduced to support backward compatibility with old erroneous implementations).

Could you please tell me a bit more about your use case? What method do you use initially (`POST`, `HEAD`, `GET`)? Why the server requires it to be changed?

**Comment by nectar1** [comment]
As you wrote if you don't want to change the request method you can use 307 answer. 

But for backward compatibility on 302 client POST is changed on GET.
On 302 status code **iOS NSUrlSession** changes method on GET... I think this case must be supported

**Comment by nectar1** [comment]
@dmitrievanthony could you please help with it?
As I said there is 302 status for support backward compatibility and also iOS NSUrlSession support this case and we can't not use ktor by this issue

**Comment by nectar1** [comment]
Also please note that on 302 Response cookies are not applied on Android, but it is ok for iOS

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
`POST` redirect is prohibited to be handled automatically according to the spec.
