### ISSUE TITLE
How to support internationalization?

### ISSUE THREAD

**Issue by contrudar** [ktorio/ktor#1667]
Couldn't find in the official docs how to support i18n. Is there something out the box? or can you advice what to use?

Use case a pretty common, a server gets request and from the header we can get locale, so we should get a right string by the locale and send corresponding response to the client.

Thanks in advance.

**Comment by cy6erGn0m** [comment]
At the moment, it's only `call.request.acceptLanguageItems()` that provides a sorted list of accepted locales provided by a peer. 

There is also incomplete PR #1632 . Hope we'll accept it one day.

**Comment by aymanizz** [comment]
Hi,

The PR has been open for quite some time and I found myself in need for this feature. I've since made my own feature to support internationalization in my app. If anyone is in a similar situation, I've recently refactored it into a separate library and published it, you can find it [here](https://github.com/aymanizz/ktor-i18n).

**Comment by e5l** [comment]
Merged
