### ISSUE TITLE
Kotlin 1.3.70

### ISSUE THREAD

**Issue by IgorKey** [ktorio/ktor#1699]
Need to update kotlin dependencies up to 1.3.70
https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/

**Comment by saschpe** [comment]
Apart from the usual iOS / macOS Framework woes, Ktor still works like a charm. However, if _KotlinX.Serialization_ is used, it needs to be updated to version 0.20.0 in conjunction with the Kotlin update

**Comment by GCoder12** [comment]
So when I just try that 
```
HttpClient(MockEngine) {
    install(JsonFeature) {
        serializer = KotlinxSerializer()
    }
}
```

using My TestModel class that is marked @Serializable I get the following error:

io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class com.ntent.artemis.TestModel
with response from http://test.api/stuff:
status: 200 OK
response headers: 
at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:79)

**Comment by GCoder12** [comment]
> kotlinx.serialization 0.20.0 and kotlin 1.3.70 are not compatible with 0.14.0 and ktor 1.3.1. Absolutely no way.

Alright well thanks for that, I missed it yesterday.  To me that is very confusing because ktor does uses the kotlinx.serialization plugin for marking data classes serializable.  But then you can't use the runtime dependency of kotlinx.serialization.

After many attempts I finally get the runtime of kotlinxserial and ktor are not compatible.  I was only interested in the latest 0.20.0 version of kotlinx.serialization runtime also, for the making custom serializers.

**Comment by IgorKey** [comment]
@cy6erGn0m  any updates about release date?
are there any snapshot or EAP repositories with 1.3.70? I really want to prepare my repos with 1.3.70 and ktor

**Comment by tak1234** [comment]
> We are waiting for kotlinx.coroutines build with 1.3.70 first

kotlinx.coroutines release new version support kotlin 1.3.70
https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.4

**Comment by IgorKey** [comment]
Any updates??

**Comment by ScottPierce** [comment]
As mentioned, a few days ago they released kotlinx.coroutines for 1.3.70. When are we going to see this for ktor?

**Comment by IgorKey** [comment]
Ok. 1.3.2 release. Thank u.
