### ISSUE TITLE
Non-blocking file download and upload support

### ISSUE THREAD

**Issue by fzoli** [ktorio/ktor#1703]
**Subsystem**
Server side, `ktor-http-jvm` module.

**Is your feature request related to a problem? Please describe.**

**1) Upload**

Ktor supports `multipart/form-data` so we can handle uploaded files using `PartData.FileItem.streamProvider` from package `io.ktor.http.content`.
The only problem with this that it provides `InputStream` that **blocks**.
Is it possible to create an other extension method that provides `Flow<ByteBuffer>`?

**2) Download**

We can serve small files using this extension method:
`suspend fun ApplicationCall.respondBytes(contentType: ContentType? = null, status: HttpStatusCode? = null, provider: suspend () -> ByteArray)`

Is it possible to provide an extension method like this to support large files?
`suspend fun ApplicationCall.respondBytes(contentType: ContentType? = null, status: HttpStatusCode? = null, provider: () -> Flow<ByteBuffer>)`

**Motivation to include to ktor**
Downloading/uploading files from smartphones can take a lot of time because the mobile internet can be really slow. **Non-blocking** solution could help a lot in these cases.

**Comment by cy6erGn0m** [comment]
1. This should be fixed, right. Currently, the only way is to use `parseMultipart` that is slightly low-level but could be used in case of urgency. 
Note that `PartData.FileItem` actually provides a blocking stream from a local file, not from the network. So the impact is very limited since files I/O is always synchronous due to OS limitations.

2. `respondBytes` is for byte arrays. For responding files use `respondFile`. For custom streaming write your `OutgoingContent` implementation that writes to or provides a `ByteChannel`.  Perhaps, we may provide `respondBytes { channel -> }` or `respondChannel(channel)`.

Allocating a lot of ByteBuffer is not that good so using `Flow<ByteBuffer>` is not recommended for large streams.

**Comment by fzoli** [comment]
> Allocating a lot of ByteBuffer is not that good so using Flow<ByteBuffer> is not recommended for large streams.

Good to know. I took the idea from [R2DBC](https://github.com/r2dbc/r2dbc-spi/blob/56b29c14628e670c196527cd090b6f32649b8e2f/r2dbc-spi/src/main/java/io/r2dbc/spi/Blob.java#L65)

Anyway if I get ByteBuffer chunks I have no choice.
Java world has no coroutine nor `ByteChannel` so they had no other choise. Or am I wrong?

**Comment by cy6erGn0m** [comment]
I would write something like this

```kotlin
suspend fun ApplicationCall.respondBytesFlow(
    contentType: ContentType? = null,
    status: HttpStatusCode? = null,
    flow: Flow<ByteBuffer>
) {
    respond(FlowWriterContent(flow, contentType, status))
}

private class FlowWriterContent(private val body: Flow<ByteBuffer>,
                        override val contentType: ContentType?,
                        override val status: HttpStatusCode? = null) : OutgoingContent.WriteChannelContent() {
    override suspend fun writeTo(channel: ByteWriteChannel) {
        body.collect {  buffer ->
            channel.writeFully(buffer)
        }
    }
}
```

**Comment by fzoli** [comment]
Thanks for your sample code. I tried it and it works.
Download is solved :-)
