### ISSUE TITLE
Ktor client throws JobCancellationException: Parent job is Completed when using compression and logging features

### ISSUE THREAD

**Issue by pecanw** [ktorio/ktor#1780]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-client-core-jvm:1.3.2
io.ktor:ktor-client-json-jvm:1.3.2
io.ktor:ktor-client-apache:1.3.1"
io.ktor:ktor-client-encoding-jvm:1.3.2
io.ktor:ktor-client-features:1.3.2
io.ktor:ktor-client-serialization-jvm:1.3.2
io.ktor:ktor-client-auth-jvm:1.3.2
io.ktor:ktor-client-logging-jvm:1.3.2

**Describe the bug**
When using the gzip compression feature together 
with the logging feature (with `LogLevel.ALL`) the client fails with the 
`kotlinx.coroutines.JobCancellationException: Parent job is Completed` exception.

**To Reproduce**
Get [ktorGzipTest](https://github.com/pecanw/ktorGzipTest) repository and run `log_all_with_gzip` test. See also readme in the repo for more details.

**Expected behavior**
The httpClient call ends successfully even when using gzip together with logging all details.

**Comment by dmitrievanthony** [comment]
Hi @pecanw, thanks for reporting!

I reproduced the issue and figured out that the root cause is this completion:

https://github.com/ktorio/ktor/blob/764cad998700430f54f3e6c77edb53159d75d7c3/ktor-client/ktor-client-core/common/src/io/ktor/client/features/observer/ResponseObserver.kt#L57-L59

Investigating the reason why these lines were added so far.

**Comment by dmitrievanthony** [comment]
Hi @e5l, as far as I understand you fixed this issue in your branch, didn't you? Can we link the corresponding PR here?

**Comment by avently** [comment]
Hello. What's a state of the issue? Is it fixed somewhere? Because for now the only way to use Gzip is to use Java's implementation of it

**Comment by e5l** [comment]
Hey @avently, the fix is done, but it is not released yet.
There is a workaround:
You can use:
```
client.request<HttpStatement>(...).execute { response -> HttpResponse
     val data = response.receive<MyDataClass>()
}
```

**Comment by avently** [comment]
Thank you, Leonid. It works

**Comment by ptsiogas** [comment]
> Hi @pecanw, thanks for reporting!
> 
> I reproduced the issue and figured out that the root cause is this completion:
> 
> https://github.com/ktorio/ktor/blob/764cad998700430f54f3e6c77edb53159d75d7c3/ktor-client/ktor-client-core/common/src/io/ktor/client/features/observer/ResponseObserver.kt#L57-L59
> 
> Investigating the reason why these lines were added so far.

@dmitrievanthony this piece of code is causing an exception:

Kotlin version 1.5.4

`failed with exception: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@d0bcbe0`

Even though I am not a coroutine expert I suspect that when HttpClientCall -> receive method is called and more specifically the part below, the job is already completed and this is causing the exception to be thrown.
This is a quite major issue because it results in randomly losing API call responses.

` val result = currentClient.responsePipeline.execute(this, subject).response`

Is there a workaround or a fix?

**Comment by e5l** [comment]
Could you file a new issue for this bug?

**Comment by ptsiogas** [comment]
> Could you file a new issue for this bug?

@e5l I have opened a new issue, you can find it [here](https://youtrack.jetbrains.com/issue/KTOR-2711).
Thanks for the support, I hope we can come to a solution because this seems like a major issue.

**Comment by e5l** [comment]
Thanks, will take a look
