### ISSUE TITLE
Optimization of Fat Jar

### ISSUE THREAD

**Issue by halimpuckjava** [ktorio/ktor#1787]
hi

when create fat jar for production, the final jar file size is more then 10Mo
so if in just add all ktor (server) dependencies and i just use 1 feature (ex: routing feature only) when create fat jar i expect a small jar (usage of 1 feature) even if in add all dependencies

how to make fat jar process smart (use only features install in ktor application not all dependencies)

**Comment by dmitrievanthony** [comment]
Hi @halimpuckjava,

I checked and as far as I see it's actually more than 10Mb. At the same time, it's due to Netty, Kotlin Stdlib&Coroutines, and other dependencies, not features you haven't included.

<img width="956" alt="Screenshot 2020-04-15 at 17 20 48" src="https://user-images.githubusercontent.com/1028969/79348263-7459db80-7f3d-11ea-9cab-f7a34d9bc873.png">
