### ISSUE TITLE
How to enable keep alive for TCP options raw socket? 

### ISSUE THREAD

**Issue by ronjunevaldoz** [ktorio/ktor#1804]
How to enable keep alive? so they the connection is not forcibly close when there is an existing connection re-connection.

```
/**
* Set TCP_KEEP_ALIVE socket option to enable the Nagle algorithm.
 */
private fun <T : Configurable<T, *>> T.tcpKeepAlive(): T {
   return configure {
       if (this is SocketOptions.TCPClientSocketOptions) {
           keepAlive = true 
           logger.debug { "Modify socket options" }
        }
    }
}

val server = aSocket(selectorManager).tcp().tcpKeepAlive().bind(socketAddress)
```

**Comment by e5l** [comment]
Hi @ronjunevaldoz, could you clarify the question? It looks like you're using the `keepAlive` flag already.

**Comment by cartermyers** [comment]
I'm running into a similar issue @e5l. What I think @ronjunevaldoz had wrong was that  `SocketOptions.TCPClientSocketOptions` is only for _client_ connections, so using it in combination as `.tcp().tcpKeepAlive().bind(socketAddress)` would not work (at least it gave me a cast exception when I tried).

What I would ultimately like is for `SocketOptions.AcceptorOptions` to provide specifying this option (since that is configurable as a parameter on the `bind` function), or some other way to customize it on the server side. 

I see that some TCP options are set in `ServerSocketImpl#accepted` (for example the java.net.Socket#setTcpNoDelay is called), so it would be nice to have things like java.net.Socket#setKeepAlive and java.net.Socket#setSoTimeout be available
