### ISSUE TITLE
Ktor sets default User-Agent even though custom one is defined in Default Headers

### ISSUE THREAD

**Issue by dtolstyi** [ktorio/ktor#1824]
**Ktor Version and Engine Used (client or server and name)**
ktor-client-apache:1.3.1

**Describe the bug**
Default _"Ktor client"_ `User-Agent` is set even if `User-Agent` header value was previously configured using `.setDefaultHeaders()` for client.

**To Reproduce**
1. Create client instance and setDefaultHeader `User-Agent`:
```
val client = HttpClient(Apache) {
    engine {
        customizeClient {
            setDefaultHeaders(mapOf(
                "User-Agent" to "Test Agent"
            ).map { BasicHeader(it.key, it.value) })
        }
    }
}
```
2. Perform any request:
```
client.request<String>("https://google.com/") {
            method = HttpMethod.Get
}
```

**Expected behavior**
Request is done using `User-Agent` that was configured for the client using default headers and not default User-Agent for Ktor

**Result**
Request is done using default Ktor UA header: `Ktor client` and not `Test Agent` that was sent when initializing client

**Code issues**
The problem is in `ktor-client-core-jvm-1.3.1-sources.jar!/commonMain/io/ktor/client/engine/Utils.kt` class. It checks if there's UA header in request itself or in content headers but never checks client default headers.
Here are the corresponding lines of code:
```
    val missingAgent = requestHeaders[HttpHeaders.UserAgent] == null && content.headers[HttpHeaders.UserAgent] == null
    if (missingAgent && needUserAgent()) {
        block(HttpHeaders.UserAgent, KTOR_DEFAULT_USER_AGENT)
    }
```

**Workaround**
Set `User-Agent` header for every request instead of setting it 1 time for the client

**Comment by dmitrievanthony** [comment]
Hi @dtolstyi, thanks for reporting! I'm fixing it, but meanwhile, as a workaround, you could use `UserAgent` feature to set the user agent:

```
install(UserAgent) {
    agent = "Test Agent"
}
```

**Comment by dtolstyi** [comment]
Thank you @dmitrievanthony!

**Comment by dmitrievanthony** [comment]
Well, @dtolstyi, I checked the root cause again and figured out that `setDefaultHeaders` is an internal configuration of the Apache client that is not available for the rest of the Ktor functionality. Unfortunately, there is no way to taking into account these Apache default headers setting up the user agent in the code you attached.

I'd recommend you to use Ktor configuration features instead of engine configuration. Particularly, in this case, as I said before, you can use the `UserAgent` feature.

**Comment by dtolstyi** [comment]
That's very sad that it cannot be fixed. The problem is that if you set Default Headers on client level then ktor will add it's headers even if they are present. This will result in duplicate headers (in our case, both User-Agents will be present in request).
Is there any need for ktor to have it's default User-Agent?

**Comment by dtolstyi** [comment]
I think we might have even more issues if one day apache client decided to set default headers themselves. Then we will have duplicates which might create issues for users.

**Comment by dtolstyi** [comment]
In `ApacheRequestProducer` class (which adds this default ktor header) we got access to `ApacheEngineConfig`. I think it's a good place in `init()` to parse config headers and add them to request, no?

**Comment by dmitrievanthony** [comment]
I understand the inconvenience, but the idea is that Ktor provides its own mechanisms to work with headers and to support all features correctly clients need to use this mechanism instead of underlying engine configuration.

Speaking about `ApacheEngineConfig`, the problem is that default headers are private and we can't extract them from this config.

**Comment by dtolstyi** [comment]
I see. Thank you for your answer @dmitrievanthony. Should we use `defaultRequest` block to specify default headers using ktor infrastructure?
