### ISSUE TITLE
Exception message is lost on copy

### ISSUE THREAD

**Issue by ark-1** [ktorio/ktor#1912]
Hi! I encountered an issue where the exception message was lost. What happened:

- I catch `ExceptionA` with message `"a"`
- I throw `ExceptionB` with this exception as cause and message `"b"`
- In different step (?) `ExceptionB` with message `"a"` is caught. Message `"b"`  is lost

I tracked it down to `tryCopyException` function in `ExceptionConstructor.kt`. It seems it only respects the cause, not the message.

https://github.com/ktorio/ktor/blob/0f76c0130d5b12d19521e93c032652a71d898b0c/ktor-utils/jvm/src/io/ktor/util/pipeline/ExceptionConstructor.kt#L25

**Comment by ark-1** [comment]
cc @qwwdfsad

**Comment by qwwdfsad** [comment]
This is not really a bug, we cannot do much here. The problem is that we cannot potentially know whether `message` is mutated or not.

Take a look at the following toy exception:
```
HttpCodeException(val cause: Throwable, val message: String) : Exception(cause, 
"HTTP request has failed with the following reason: $message. Please consider using KtorHttpResponseHandler to gracefully handle these error codes.")
```
Do you really want here to pass `message` of the original exception to the copied one? Probably not.

Potentially, we could try to guess whether an exception message is mutated or not by introspecting constructor parameter name, but this capability is available only in Java 8 (-> not compatible with our current Android-driven target).

So whatever choice we made, there would be a code that doesn't fit this choice.
I'd recommend implementing `CopyableThrowable` in your custom exception

**Comment by ark-1** [comment]
The irony here is that your exception contains custom logic and mine does not (`class ExceptionB(message: String, cause: Throwable) : Exception(message, cause)`), and yet it is my exception that has to implement `CopyableThrowable`

**Comment by qwwdfsad** [comment]
The real irony is that we've tried the approach with invoking a constructor with String parameter unconditionally and received a lot of negative feedback because it made some 3rd-party (can't implement `CopyableThrowable` there) much harder to debug due to cumbersome messages, and yet we are here exchanging quips.

Unfortunately, decisions like this are always about trade-offs.
