### ISSUE TITLE
418, I'm a teapot not supported

### ISSUE THREAD

**Issue by radekkut** [ktorio/ktor#206]
org.jetbrains.ktor.http.HttpStatusCode does not contain the 418 I'm a teapot status code.

**Comment by hhariri** [comment]
To be honest, this is not part of the specification, and recently there has been concerns about people actually using this code for the wrong reason. It was merely a joke when it came out. I'd be hesitant in adding it. @orangy ?

**Comment by cy6erGn0m** [comment]
418 status code is described in RFC 2324 (Hyper Text Coffee Pot Control Protocol) and it's April Fools joke.

**Comment by orangy** [comment]
Also, you can add it as an extension property

    val HttpStatusCode.Companion.IAmATeaPot get() = HttpStatusCode(418, "I'm a tea pot")

**Comment by deviant-studio** [comment]
somebody should publish the lib with such extension!

**Comment by radekkut** [comment]
I dont think one line of code is worth publishing a lib

**Comment by y9san9** [comment]
Sorry for nekroposting, but 418 was formally reserved to have no other use in foreseeable future, so it is definitely safe to include that to a library (https://www.rfc-editor.org/rfc/rfc9110#name-418-unused). I believe it should be up to user whether to use that code actually or not. A lot of http libraries include that code. But I don't care much, since, again, you can define this as an extension function.
