### ISSUE TITLE
Make ktor-samples depend on maven releases instead of ktor project files

### ISSUE THREAD

**Issue by scic** [ktorio/ktor#243]
For example in the [build.gradle](https://github.com/ktorio/ktor/blob/d7482a583613977ba1507fd383416e3a6e678f44/ktor-samples/ktor-samples-gson/build.gradle) for the gson-sample is:

`compile project(':ktor-features:ktor-gson')`

Thus i can **not** just copy this code to a standalone project and run it.

Furthermore the artifacts for several modules are missing or outdated in the maven repository.
Like:
- ktor-gson
- ktor-jackson

I think by referencing the maven releases it is much easier to try out the examples and it is clear what version is needed for it to run and ensure that they exist.

**Comment by triplem** [comment]
Right now the samples are based on the current development version. This makes sure, that the latest version of the project is used in those samples as well. The samples do show off the latest developments as well. Since ktor is moving rapidly right now, I guess that it does not really makes sense to "fix" the version of the project in the samples. This should be done in external samples, not in the project structure.

**Comment by scic** [comment]
Okay. I guess it makes sense to delay this for 1.0.0. But I guess it would even be better to split the samples into its own repository. And use them as "external" samples that can be run standalone without downloading the whole ktor project. This could then also be used on external content on the website.
If the development version is needed in the samples then maybe alpha or SNAPSHOT releases of ktor could be build and used.

The reason I proposed this was because right now its hard to know where to get all the dependencies used in the samples.
For example there is no documentation what packages exist and in what maven repository they are in.
Also the sample pages like http://ktor.io/samples/jackson.html just show a 404.
