### ISSUE TITLE
can't download org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.7

### ISSUE THREAD

**Issue by jarekczek** [ktorio/ktor#341]
org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.7

I guess I was able to fetch the jar yesterday. Today I even can't fetch 'io.ktor:ktor-html-builder:0.9.1', because it depends on the above automatically.

Please fix the repo.

**Comment by Prototik** [comment]
You need to add repo `https://kotlin.bintray.com/kotlinx.html` to your buildsystem. Neither maven nor gradle will not do it for you.

**Comment by orangy** [comment]
Looks like something is not working on your end, I have no issues opening repo: https://kotlin.bintray.com/kotlinx.html/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/

**Comment by cy6erGn0m** [comment]
kotlinx.html is in **jcenter** as well

**Comment by jarekczek** [comment]
Thank you very much! It's so wonderful, when you find such a great project (kotlin + ktor) and people with quick support. Now to the merit:

1. jcenter works well
2. Gradle configuration given in ktor.io -> quick start -> [setting up gradle build](http://ktor.io/quickstart/gradle.html#add-ktor-dependencies-and-configure-build-settings)  - is outdated. Should I file another issue to fix it?
3. `maven { url "https://kotlin.bintray.com/kotlinx.html" }` is correct, but it's like having a separate maven url for a single dependency - not very convenient

Considering these points maybe jcenter should be put in the examples.

Cheers.

**Comment by soywiz** [comment]
I have replaced the `kotlinx` bintray repository to just `jcenter` in the linked PR.

Strictly, the quickstart was correct because that page doesn't refer to `kotlinx.html` at all.
But agree that having to deal with a lot of repositories for potentially each single dependency is far from ideal.
And since as far as I know both: `kotlinx.coroutines` and `kotlinx.html` are published to `jcenter`, I have changed it to be less confusing.

I'm closing this, but feel free to reopen or comment if I missed something :)

Regards, and thanks for the feedback!
