### ISSUE TITLE
App Not Autoreloading

### ISSUE THREAD

**Issue by eriknyk** [ktorio/ktor#373]
Hello I just configured a demo project to use autoreload feature, 
I followed instructions described here: https://ktor.io/servers/autoreload.html
but I couldn't to get  it working at all

please see the video: https://www.screencast.com/t/iZhs7aGSwiej

[![video demo](https://user-images.githubusercontent.com/205721/38071704-79373b6e-32e8-11e8-8b89-e0645032d728.png)](https://www.screencast.com/t/iZhs7aGSwiej)

I'm using ktor v0.9.2-alpha-3

Best Regards.

**Comment by soywiz** [comment]
Checking the video I can see the following in the logs:

```
00:24:17.364 INFO ktor.application - No ktor.deployment.watch pattern match classpath entries...
```

Watching the video I guess the problem is with your `watchPaths`. The `watchPaths` search for `.class` files. The src folder only contains source `.kt` files, so it won't match.
To to use `watchPaths = listOf("demo")` instead.

Note: If it doesn't work either, check that you are using Java8 (it doesn't work on Java9 at this point)

**Comment by eriknyk** [comment]
it works awesome, thank you! @soywiz
