### ISSUE TITLE
Can't visit files of `staticRootFolder`

### ISSUE THREAD

**Issue by freewind** [ktorio/ktor#514]
A directory with static html/css files:

```
static
├── css
│   └── index.css
├── index.html
└── index2.css
```

The code:

```
fun main(args: Array<String>) {
    val server = embeddedServer(Netty, port = 8080) {
        routing {
            static("/") {
                staticRootFolder = File("./static")
                default("index.html")
            }
        }
    }
    server.start(wait = true)
}
```

When visiting <http://localhost:8080>, only `index.html` found. The other files (css files) not found.

I have to add `files(".")` after `staticRootFolder = File("./static")` to make it work, and this feels a little strange.

**Comment by cy6erGn0m** [comment]
It should be

```
statuc("/") {
    files("static")
    default("static/index.html")
}
```

**Comment by freewind** [comment]
So we don't use `staticRootFolder` in this case. When to use it?

**Comment by TWiStErRob** [comment]
I agree with @freewind's first block of code, that's what I ended up with too and needed `files(".")`. Note that while `default("static/index.html")` is more explicit, there's unnecessary duplication in it. What `default("index.html")` expresses to me is "It doesn't matter where my files are coming from, I'll still want `index.html` to be the default."

But @cy6erGn0m's 
> Note that default() function is not applied to subdirectories

bit me. If that's true, how can I serve multiple folders' `index.html` like other webservers without listing them explicitly?

**Comment by TWiStErRob** [comment]
[This](https://youtrack.jetbrains.com/issue/KTOR-2401) is now fixed in https://github.com/ktorio/ktor/pull/3425 as part of https://youtrack.jetbrains.com/issue/KTOR-5265 in Ktor 2.3.0

There's an explicit test for nested index handling (but only for `staticResources`, not for `staticFiles` cc @rsinukov):
https://github.com/ktorio/ktor/blob/1cbe6787e39158fbb9184c0f8863861f542f96ec/ktor-server/ktor-server-tests/jvm/test/io/ktor/server/plugins/StaticContentTest.kt#L340-L342

After removing the workaround for this issue, I've also confirmed with my own tests that the new DSL fixes this issue. There's no need for `files(".")` nor `default` calls.
