### ISSUE TITLE
KotlinxSerializer fails to parse JSON on iOS

### ISSUE THREAD

**Issue by samus** [ktorio/ktor#632]
The utf-8 charset parameter should be passed to the readText method in the response otherwise an error will happen on iOS complaining that the character set is not utf-8 which is required for JSON.

KotlinXSerializer.kt
val text = response.readText(charset = Charsets.UTF_8)

**Comment by yuriry** [comment]
@samus I'm running into [this problem](https://github.com/ktorio/ktor/issues/626) when building an iOS framework with ktor.  Since you can run your project on iOS, could you please share the configuration that you use to compile the project? I'm looking for kotlin_version, kotlin_native_version, ktor_version and serialization_version. Thank you in advance!

**Comment by samus** [comment]
I can actually share the full code since it is just a demo app for conference talk I'm giving soon.  https://github.com/samus/mpp_chuck_demo

**Comment by yuriry** [comment]
@samus Thank you for sharing the project, it was very helpful.  My undefined symbols problem was resolved by changing ```ext.ktor_version = "0.9.5-rc13"``` to ```ext.ktor_version = "0.9.5-rc13-conf2"```.  It may still fail at run time as mentioned by @Alex009, but at least it is a step forward.

**Comment by e5l** [comment]
Fixed in `1.0.0-alpha-3`
