### ISSUE TITLE
Ktor-Client-Js: Upload ktor-client-js library to npm 

### ISSUE THREAD

**Issue by salztorte** [ktorio/ktor#657]

**Comment by e5l** [comment]
Hi, @salztorte. Thanks for the report.

**Comment by lamba92** [comment]
Yes please! Otherwise it's impossible to share libraries as Node Packages.
My use case is to build a common library for Android and web and the web frontend uses Angulajs. 
Of course without Ktor client on NPM I must copy the extracted artifact with my library output and always carry it with me.

I do realize that this is a much broader problem that probably need guidance from the Kotlin team. Still, publishing on NPM every MPP  library counterpart seems a good start imo.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-736">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
