### ISSUE TITLE
Can't read JSON response with wrong Content-Type

### ISSUE THREAD

**Issue by tinchou** [ktorio/ktor#772]
### Ktor Version

`1.0.0`

### Ktor Engine Used(client or server and name)

Any client (tried both `Apache` and `CIO`)

### JVM Version, Operating System and Relevant Context

```
macOS Mojave 10.14.1
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### Repro

1. Take the JSON example from https://ktor.io/clients/http-client/examples.html#example-json
2. Change the server response to `call.respondText("{\"hello\": \"response\"}", ContentType.Text.Html)`

### Feedback

I have to talk to an API that returns a JSON body but also sets the following header: `Content-Type: text/html; charset=utf-8`.

When I send a POST request and try to get the JSON object back (using `JsonFeature`), it fails regardless of the actual implementation (`Jackson`, `GSON`, etc.). I get the following error message:

```
io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.client.engine.cio.CIOHttpResponse -> class my.package.MyDataClass
```

I tried setting `accept(ContentType.Application.Json)` in the POST request configuration block with no success. Any workaround would be appreciated too!

**Comment by cy6erGn0m** [comment]
It doesn't work because of the following line https://github.com/ktorio/ktor/blob/12c1bdf547b193726a7d7df1aeee424eb81da98e/ktor-client/ktor-client-features/ktor-client-json/src/io/ktor/client/features/json/JsonFeature.kt#L61

So possible workarounds are:
- write your custom `JsonFeature` (it looks quite simple, isn't it?)
- write a feature to replace response content type so JsonFeature could handle it properly

I'd say the first workaround is easier to do

**Comment by tinchou** [comment]
> write your custom `JsonFeature` (it looks quite simple, isn't it?)

Yes it does, thank you for pointing it out!

I would love to stay in the loop and see how the design moves forward. I'll come back if I have any ideas :)

**Comment by e5l** [comment]
Looks like resolved :)
