### ISSUE TITLE
SessionTransportTransformerDigest is unsafe

### ISSUE THREAD

**Issue by veeti** [ktorio/ktor#792]
`SessionTransportTransformerDigest` provides cookie authentication using a simple hash construction potentially vulnerable to length extension attacks. Since `SessionTransportTransformerMessageAuthentication` already exists and uses a proper HMAC, digest should be deprecated and removed.

**Comment by cy6erGn0m** [comment]
Current ktor implementation makes it more difficult to apply this exploit due to unmappable UTF8 characters (such as 0x80) that causes hash to not match. Do you know, is it possible to improve this kind of attack to generate an _extension_ from printable ascii characters only?

Also it should be noted that not all hash algorithms are vulnerable, for example SHA-384 and SHA-3 are not the case.

The obvious solution is to deprecate `SessionTransportTransformerDigest` so I'd apply it. The other solution is to prohibit insecure hash functions during construction. 

We also need to analyze other parts such as Digest Auth to check if it is vulnerable or not.

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.0

**Comment by kostrse** [comment]
[Transformers](https://ktor.io/docs/transformers.html#standard-transformers) documentation still doesn't mention that SessionTransportTransformerDigest has been deprecated and it's the first choice there.
